import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const prompt = Prompt({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-white min-h-screen ${prompt.className} antialiased`}
      >
        <nav className="p-4 fixed top-0 w-full h-16 items-center bg-white shadow-md flex justify-between text-gray-900">
          <Link href={"/"} className="text-xl font-bold">My Portfolio</Link>
          <div className="space-x-6">
            <Link href="/about">About</Link>
            <Link href="/projects">Projects</Link>
            <Link href="/contact">Contact</Link>
          </div>
        </nav>
        <div className="pt-16 min-h-screen flex flex-col justify-between bg-gray-900">
          {children}
          <footer className="p-4 bg-gray-900 text-white text-sm font-light text-center">
            <p>&copy; {new Date().getFullYear()} My Portfolio</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
